{% set name = "postgis" %}
{% set version = "3.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 71d8f5d06debec0bdd94525a5a1d42417ed2a1f65d0070a1a3e3e381b606ee35

build:
  number: 0
  skip: True  # [s390x]  # missing libgdal

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - autoconf
    - automake
    - libtool
    - make
    - perl 5.*
  host:
    - libxslt
    - cunit
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - postgresql
    - libpq
    #DDD
    - pcre2
    - libiconv
    - libxml2
  run:
    - libgdal
    - geos
    - gettext
    - pcre
    - proj
    - json-c
    - postgresql
    - libpq

  test:
    commands:
      - test -f $PREFIX/bin/pgsql2shp   # [linux or osx]
      - test -f $PREFIX/bin/pgtopo_export   # [linux or osx]
      - test -f $PREFIX/bin/pgtopo_import   # [linux or osx]
      - test -f $PREFIX/bin/postgis   # [linux or osx]
      - test -f $PREFIX/bin/postgis_restore   # [linux or osx]
      - test -f $PREFIX/bin/raster2pgsql   # [linux or osx]
      - test -f $PREFIX/bin/shp2pgsql   # [linux or osx]

      - test -f $PREFIX/lib/postgis-3.dylib  # [osx]
      - test -f $PREFIX/lib/postgis_topology-3.dylib  # [osx]
      - test -f $PREFIX/lib/postgis_raster-3.dylib  # [osx]
      - test -f $PREFIX/lib/address_standardizer-3.dylib  # [osx]

# test:
#   files:
#     - test_data
#     - run_test.sh
#   commands:
#     - sh run_test.sh
#     # - shp2pgsql test_data/test.shp
#     # - pgsql2shp
#     # - raster2pgsql

about:
  home: http://postgis.net
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.TXT
  summary: PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.
  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/documentation/
  dev_url: https://git.osgeo.org/gitea/postgis/postgis

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
    - xylar
    - mxr-conda
