{% set name = "postgis" %}
{% set version = "2.4.3" %}
{% set sha256 = "ea5374c5db6b645ba5628ddcb08f71d3b3d90a464d366b4e1d20d5a268bde4b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://download.osgeo.org/{{ name }}/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-gdal-test.patch

build:
  number: 0
  skip: True  # [ win ]

requirements:
  build:
    - cunit
    - gdal
    - geos
    - gettext
    - pcre
    - proj4
    - json-c {{ json_c }}
    - perl
    - postgresql {{ postgresql }}
    - toolchain
  run:
    - gdal
    - geos
    - gettext
    - pcre
    - proj4
    - {{ pin_compatible('json-c') }}
    - postgresql

test:
  commands:
    - shp2pgsql
    - pgsql2shp
    - raster2pgsql

about:
  home: http://postgis.net
  license: GPL2
  license_family: GPL
  license_file: LICENSE.TXT
  summary: 'PostGIS adds geometry, geography, raster and other types to the PostgreSQL database.'

  description: |
    PostGIS is a spatial database extender for PostgreSQL object-relational
    database. It adds support for geographic objects allowing location
    queries to be run in SQL.
  doc_url: http://postgis.net/docs/manual-2.3/
  dev_url: http://svn.osgeo.org/postgis/

extra:
  recipe-maintainers:
    - sodre
    - dwnoble
