travis:
  secure:
    BINSTAR_TOKEN: pKr4nkg/zbs/9GR53sY/qLwg/Z8AS0Pry5NTHX0PZgJSg7Bp+Lx0qTZXCDlN+/IJhHDTlUqdTieSGCRWJnqXFhECEn1gtqMh5Rl8za7fh3xuBAL2jdU8U5sDwDIPNPSow2D2jlMlvxC/1JiiTOWWkXN3oUb22jabjCa10zKu23I01dotZzoXD/5DNngTRtdiGMdqMDZP846xDhFup58CQTAao8DpMPhMCE3i4xMgC1TrGeGbQU9dQ/Hv4syJM2ceslkyZ3O7s6UB+p8FHrxGy5hA3Ac0XpkohLFBIcDXR25MLWPKl/yA4rG0M1TK78Eoh8cAystNVFoug52KHGBHjWEOkSYwDsDXlq8Cwn5d7/tfIoLWiG7dlR0ciCrmNp4f/7Iu3r+Juw5VEKem7FB8o9tOVS9RkpqNUiefgEUHpSTs2tXXizhZlhTbvAzs94HezJIJ9GdAhOaL0HkTJtiAYp1moNo/hLMtMndcXKEHxMmoq+blqoOI/P5DW5pn0ENrv5PEiQkF7KWxdLjAMORUzUQDhQH6mg1IUBGe+p8t/NKGD5WMyBXAb7HhuQBVUyY5WMNnT1bo20A3V9vRbcM6hrj+Ibc6xO1A9+R5a0mSBwBj0MMeC5wn8VFuKypzA7XxxpFhrxCMNkh61w8tVrnFeJqxjypuFMjhi+WFsWvG0Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
